### ISSUE TITLE
Debrief GPR1

### ISSUE THREAD

**Issue by ThomasGrossmann** [ThomasGrossmann/GPR1-SocialNetwork#1]
[02be5ee](https://github.com/ThomasGrossmann/GPR1-SocialNetwork/commit/02be5eedaed6d31f2a882ece7e1f93c54e0ff258)

Analyse :
Le test "test_constructor_InstantiationWithDuplicatedSubscribers_ThrowsException" se passe au niveau du constructeur. Au moment de créer un nouveau élément il va venir rajouter un objet dupliqué (qui sera donc le même qu'un objet déjà présent) 

Je n'ai pas su s'il fallait faire une condition dans le constructeur ou ailleurs.

**Comment by NicolasGlassey** [comment]
@ThomasGrossmann 

Bonjour Thomas,

J'ai bien pris en compte votre issue pour l'évaluation.

Bonne suite de week-end !
Nicolas Glassey
